### ISSUE TITLE
Select ES6 testing framework

### ISSUE THREAD

**Issue by ProfessorO** [ProfessorO/esperanta-analizisto#5]
Jasmine, Karma, something else?

**Comment by stephenwade** [comment]
So many tool options!

Here's another one to look at: [web-component-tester](https://github.com/Polymer/web-component-tester)

**Comment by stephenwade** [comment]
I think our tests will be better implemented at a higher level, like suggested in #27.

What we really need to test is whether specific words parse correctly (as regression testing), and this will be better implemented in the GUI/Firebase, since we need to quickly be able to add tests (click to indicate that this word is parsed correctly, rather than go to the code and add a new line to the test file).

Therefore, I'm closing this.
